apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docker-test-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          # Frontend
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: docker-test-fe-ser
                port:
                  number: 5144

          # Backend
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: docker-test-be-ser
                port:
                  number: 8085


